"""Curated OSINT aliases keyed by ITM technique / subsection id.

Titles from the matrix are always included as aliases by the refresh
step; this map adds phrasing commonly seen in public reporting.
"""

from __future__ import annotations

# Aliases that are too generic to independently signal insider behaviour — they
# flood false positives when matched against long court documents (e.g. a
# gambling-regulation suit says "gambling"; a data-breach class action says
# "browsers"/"firmware"; an employment case says "authorized leave"). The ITM
# matcher skips these as standalone triggers (both single tokens and phrases);
# richer, context-bearing aliases still match. Deliberately EXCLUDES terms that
# carry real insider signal even alone (e.g. "outside employment" → IF038,
# "remote desktop protocol" → PR026).
GENERIC_ALIAS_STOPLIST: frozenset[str] = frozenset(
    {
        # ultra-generic single tokens (original inline stoplist)
        "access",
        "theft",
        "printing",
        "placement",
        "stalling",
        "virtualization",
        "tripwires",
        "espionage",
        "sabotage",
        "bribe",
        "snooping",
        # over-broad ITM technique titles that match incidental mentions
        "gambling",
        "gaming",
        "browsers",
        "firmware",
        "conflicts of interest",
        "authorized leave",
        "unauthorized leave",
        "unauthorized third party",
    }
)

# Extra match phrases for high-signal OSINT wording (lowercase).
CURATED_ALIASES: dict[str, tuple[str, ...]] = {
    # Motive
    "MT003": (
        "leaver",
        "departing employee",
        "departing staff",
        "resignation",
        "offboarding",
        "former employee",
        "ex-employee",
        "left the company",
    ),
    "MT005": ("personal gain", "financial motive", "sold data", "sold credentials", "bribe"),
    "MT012": ("coercion", "blackmail", "extortion of employee"),
    "MT015": ("recklessness", "negligent insider", "careless employee"),
    "MT017": (
        "espionage",
        "nation-state insider",
        "foreign intelligence",
        "passed secrets",
        "state secrets",
    ),
    "MT022": ("boundary testing", "policy testing", "pushing boundaries"),
    # Means
    "ME001": ("unassigned hardware", "orphan device", "unallocated asset"),
    "ME003": ("installed software", "local software", "desktop application"),
    "ME004": ("bluetooth", "bt exfil", "wireless pairing"),
    "ME005": ("removable media", "usb", "thumb drive", "flash drive", "external drive"),
    "ME006": ("web access", "web browsing", "internet access"),
    "ME014": ("printing", "print job", "printer"),
    "ME016": ("firmware", "bios", "uefi", "bootkit"),
    "ME021": (
        "unrevoked access",
        "orphan account",
        "leftover access",
        "stale access",
        "retained access",
        "access after employment",
    ),
    "ME024": ("system access", "account access", "privileged access"),
    "ME027": ("credential access", "credential exposure", "password dump", "credential leak"),
    "ME030": ("enterprise ai", "copilot", "corporate llm", "ai platform", "shadow ai"),
    # Preparation
    "PR002": ("device mounting", "mount usb", "mounted volume"),
    "PR003": ("software installation", "install software", "installed package"),
    "PR004": ("file exploration", "browsing files", "directory enumeration"),
    "PR006": ("security software enumeration", "edr discovery", "av enumeration"),
    "PR014": ("media formatting", "format usb", "format drive"),
    "PR015": ("email collection", "mailbox export", "pst export"),
    "PR016": ("data staging", "staging folder", "staged files", "archive staging"),
    "PR017": ("archive data", "zip archive", "rar archive", "7z archive"),
    "PR018": ("circumventing security", "bypass dlp", "dlp bypass", "security bypass"),
    "PR020": ("data obfuscation", "obfuscate data", "encrypt before exfil"),
    "PR022": (
        "social engineering",
        "pretexting",
        "phishing outbound",
        "posing as it support",
        "help desk impersonation",
        "help desk social engineering",
        "vishing",
    ),
    "PR024": ("increase privileges", "privilege escalation", "elevate privileges"),
    "PR025": (
        "file download",
        "mass download",
        "bulk download",
        "downloaded confidential",
        "downloaded engineering documents",
    ),
    "PR026": ("remote desktop", "rdp", "remote desktop protocol"),
    "PR027": (
        "impersonation",
        "account impersonation",
        "spoofed identity",
        "sim swap",
        "sim swapping",
    ),
    "PR028": ("on-screen data", "screen scrape", "ocr capture"),
    "PR035": ("ai agent", "delegated ai", "ai preparation"),
    "PR037": ("oversight circumvention", "disable monitoring", "control degradation"),
    "PR041": (
        "credential collection",
        "credential theft",
        "steal credentials",
        "harvest credentials",
        "password harvest",
        "cloud credentials",
        "stolen credentials",
        "browser credentials",
        "credential dump",
        "ai credentials",
    ),
    "PR042": ("account creation", "created account", "new user account"),
    # Infringement
    "IF001": (
        "exfiltration via web",
        "web exfiltration",
        "upload to web",
        "saas exfil",
        "data exfiltration",
    ),
    "IF001.001": (
        "cloud storage exfil",
        "dropbox upload",
        "google drive upload",
        "onedrive upload",
    ),
    "IF002": ("exfiltration via physical", "usb exfiltration", "walked out with data"),
    "IF003": ("media capture", "photograph screen", "phone camera"),
    "IF004": ("network exfiltration", "covert channel", "dns exfil"),
    "IF005": ("messaging exfiltration", "slack exfil", "teams exfil", "whatsapp exfil"),
    "IF006": ("unauthorized printing", "printed documents", "print sensitive"),
    "IF008": ("inappropriate browsing", "forbidden sites", "policy-violating web"),
    "IF009": ("unapproved software", "shadow it install", "unauthorized software"),
    "IF010": (
        "exfiltration via email",
        "email exfil",
        "forwarded to personal",
        "personal email forward",
    ),
    "IF011": ("third party access", "shared access externally", "unauthorized third party"),
    "IF012": ("brand damage", "public statement", "leaked to press"),
    "IF013": ("business disruption", "disrupted operations", "operational sabotage"),
    "IF014": ("unauthorized changes", "unauthorized config", "rogue change"),
    "IF015": (
        "theft",
        "stole equipment",
        "asset theft",
        "stole confidential",
        "trade secret theft",
        "stole secrets",
        "pattern of theft",
    ),
    "IF016": ("misappropriation", "embezzlement", "stole funds"),
    "IF018": (
        "ai chatbot",
        "chatgpt leak",
        "shared on chatgpt",
        "llm data leak",
        "shadow ai",
    ),
    "IF022": ("data loss", "lost data", "accidental disclosure"),
    "IF023": ("regulatory non-compliance", "compliance violation", "gdpr breach"),
    "IF025": ("internal credential sharing", "shared password", "password sharing"),
    "IF026": ("denial of service", "insider dos", "availability attack"),
    "IF027": ("malicious software", "installed malware", "logic bomb"),
    "IF028": ("ai agent execution", "delegated execution", "ai-driven infringement"),
    "IF029": ("codebase integrity", "source code sabotage", "malicious commit"),
    "IF033": ("digital defacement", "defaced", "website defacement"),
    "IF035": ("unauthorized work location", "remote from banned country", "geo policy violation"),
    "IF036": ("misuse of communication", "abuse of email", "corporate channel misuse"),
    "IF037": ("physical sabotage", "sabotage", "damaged equipment"),
    # Undisclosed concurrent employment — OSINT / filings / investigator hunt phrases
    "IF038": (
        "overemployment",
        "over-employment",
        "over employed",
        "overemployed",
        "moonlighting",
        "moonlight",
        "moonlighting policy",
        "side job",
        "side hustle",
        "second job",
        "dual employment",
        "concurrent employment",
        "undisclosed employment",
        "undisclosed concurrent employment",
        "secret second job",
        "multiple jobs",
        "working two jobs",
        "two jobs",
        "outside employment",
        "outside employment policy",
        "outside employment disclosure",
        "conflict of interest disclosure",
        "coi disclosure",
        "secondary employment",
        "additional employment",
        "J2",
        "job 2",
        # Competitor / side-work adjacent (often co-travels with IF038 in disputes)
        "side project competitor",
        "consulting on the side",
        "advisory role undisclosed",
    ),
    "IF039": (
        "unauthorized account access",
        "accessed another account",
        "account takeover insider",
        "unauthorized access to patient",
        "accessed patient records",
        "snooping",
        "looked up records",
    ),
    # Anti-forensics
    "AF001": ("clear command history", "history -c", "destroyed bash history"),
    "AF002": ("log deletion", "deleted logs", "cleared event logs"),
    "AF004": ("clear browser artifacts", "cleared browser history", "private browsing wipe"),
    "AF006": ("disk wiping", "wiped disk", "secure erase"),
    "AF007": ("modify registry", "registry edit", "regedit"),
    "AF008": ("steganography", "hidden in image", "stego"),
    "AF011": ("destroyed storage", "shredded drive", "physical media destruction"),
    "AF012": ("hide artifacts", "hidden files", "artifact concealment"),
    "AF013": ("delete user account", "deleted account", "account removal"),
    "AF018": ("tripwire", "canary token", "detection tripwire"),
    "AF022": ("virtualization", "vm wipe", "ephemeral vm"),
    "AF024": ("account misuse", "misused account", "shared admin account"),
    "AF027": ("clear email artifacts", "deleted emails", "purged mailbox"),
    "AF028": ("stalling", "delayed response", "investigation stall"),
    "AF029": (
        "network obfuscation",
        "proxy chaining",
        "traffic obfuscation",
        "vpn evasion",
        "anonymization",
        "ip masking",
        "residential proxy",
        "ngrok",
        "unmonitored network",
        "switching networks",
    ),
    "AF030": ("message deletion", "deleted messages", "chat wipe"),
    "AF031": ("code obfuscation", "commit obfuscation", "misrepresented contribution"),
    "AF032": ("system time modification", "clock skew", "timestomp clock"),
}

# Framing terms that boost insider-relevance even without a technique hit.
INSIDER_FRAMING_KEYWORDS: tuple[str, ...] = (
    "insider threat",
    "insider risk",
    "malicious insider",
    "negligent insider",
    "insider attack",
    "insider breach",
    "insider incident",
    "privileged user abuse",
    "departing employee",
    "former employee",
    "ex-employee",
    "unauthorized access",
    "trade secrets",
    "confidential information",
    "patient records",
    "snooping",
    # Attribution-forensics: persistent device/telemetry artifacts that
    # deanonymize an actor despite VPNs (e.g. the Windows GDID Scattered
    # Spider case). Signals the reporting is investigation-grade.
    "device fingerprint",
    "device identifier",
    "digital fingerprint",
    "deanonymization",
    "telemetry identifier",
)
