/* Sample corpus for the redesign prototype — fictional but structurally faithful. */
window.II_DATA = {
  status: { corpus: 4812, methodBearing: 1207, adjudicated: 318, lastIngest: "2026-08-10 06:00Z", nextSweep: "12:00Z", lanes: [["COURT FILINGS", "OK"], ["NEWS", "OK"], ["SOCIAL", "OK"], ["PUBLICATIONS", "OK"]] },
  techniques: {
    IF002: { theme: "Infringement", name: "Exfiltration via Cloud Storage", desc: "Company data synced or uploaded to a personal cloud storage account.", detections: [["DT046", "Cloud-app audit: uploads to non-corporate tenants"], ["DT011", "Endpoint: rclone / sync-client execution"], ["DT052", "Egress volume anomaly vs. peer baseline"]], preventions: [["PV019", "Block unsanctioned cloud storage at proxy"], ["PV004", "DLP on archive + bulk upload"]], hunts: ["Sweep cloud-app logs for personal-tenant destinations in the 30 days before any resignation date.", "Alert on first-seen sync binaries (rclone, Dropbox CLI) on hosts outside engineering baselines.", "Join HR departure list against egress-volume outliers; review top decile manually."], corr: true },
    IF001: { theme: "Infringement", name: "Exfiltration via Personal Email", desc: "Files forwarded or attached to a personal webmail account.", detections: [["DT003", "Mail gateway: attachments to freemail domains"], ["DT052", "Egress volume anomaly"]], preventions: [["PV004", "DLP on outbound attachments"]], hunts: ["Search gateway logs for freemail recipients receiving attachments over 5 MB from departing staff.", "Flag self-addressed mail patterns (same display name, external domain)."], corr: true },
    IF038: { theme: "Infringement", name: "Undisclosed Concurrent Employment", desc: "Working a second job in parallel without disclosure, on company time or equipment.", detections: [["DT061", "Calendar/meeting overlap patterns"], ["DT033", "VDI session concurrency from one endpoint"]], preventions: [["PV027", "Conflict-of-interest attestation cycle"]], hunts: ["Correlate badge/VPN idle hours against sustained calendar declines.", "Look for input-automation tooling (jigglers, macro apps) in endpoint inventory."], corr: false },
    ME021: { theme: "Means", name: "Credential Sharing", desc: "Logins, badges, or tokens shared with or borrowed from another person.", detections: [["DT018", "Impossible-travel / concurrent session on one account"], ["DT025", "Badge-in without corresponding workstation auth"]], preventions: [["PV009", "Phishing-resistant MFA, no shared service accounts"]], hunts: ["List accounts with interactive logons from more than two distinct endpoints per shift.", "Reconcile badge events against auth events per person-day; investigate systematic gaps."], corr: true },
    ME024: { theme: "Means", name: "Dormant Privileged Account", desc: "Access retained or re-enabled after role change or separation.", detections: [["DT029", "Auth from accounts past separation date"], ["DT041", "Privileged group membership drift"]], preventions: [["PV013", "Joiner-mover-leaver dedaily reconciliation"]], hunts: ["Diff IAM directory against HR roster weekly; any auth from a separated identity is a finding.", "Audit re-enable events on admin accounts outside change windows."], corr: true },
    ME027: { theme: "Means", name: "Access Beyond Need", desc: "Authorized credentials used to browse records outside job function.", detections: [["DT037", "Record-access volume vs. role baseline"]], preventions: [["PV021", "Break-glass audit on sensitive record classes"]], hunts: ["Rank record lookups per user against role cohort; review top outliers with no case assignment."], corr: false },
    ME030: { theme: "Means", name: "Unsanctioned AI Tooling", desc: "Company material pasted into personal or unapproved AI services.", detections: [["DT058", "Proxy: POST bodies to consumer AI endpoints"], ["DT011", "Clipboard-scale paste events into browser sessions"]], preventions: [["PV031", "Sanctioned AI gateway with logging"]], hunts: ["Inventory proxy hits to consumer AI domains from finance/legal segments; sample sessions.", "Deploy canary strings in sensitive docs; watch for them in AI-provider breach corpora."], corr: false },
    PR003: { theme: "Preparation", name: "Data Staging", desc: "Archives or bulk copies assembled locally ahead of exfiltration.", detections: [["DT014", "Endpoint: mass archive creation (zip/7z/tar)"], ["DT046", "Staging directories with anomalous byte counts"]], preventions: [["PV004", "DLP on archive creation over thresholds"]], hunts: ["Hunt for archive creation touching source-code or CRM paths by non-build accounts.", "Trace archives created within 14 days of a resignation notice."], corr: true },
    AF014: { theme: "Anti-Forensics", name: "Log and History Deletion", desc: "Shell history, browser history, or audit logs cleared to obscure activity.", detections: [["DT022", "Audit-log clear events (1102/104)"], ["DT011", "history -c / .bash_history truncation"]], preventions: [["PV016", "Forward logs off-host at write time"]], hunts: ["Alert on any 1102 event; on Unix fleets, diff shell-history file sizes across nightly snapshots.", "Treat gaps in per-host telemetry during known incident windows as staging evidence."], corr: true }
  },
  cases: [
    { id: "2026-0806-K4F", kind: "CASE", title: "Meridian Biolabs, Inc. v. Chen", channel: "filings", sig: 91, strength: "CONFIRMED IN COURT", source: "COURTLISTENER RECAP", docket: "N.D. CAL. 5:26-CV-04471", filed: "2026-08-06", retrieved: "2026-08-09 14:32Z", insiderType: "malicious", note: "Principal scientist synced 41 GB of assay protocols and a compound library to a personal Dropbox over nine days before resigning to join a competitor. Staging archives were assembled on a lab workstation after hours; shell history on the host was cleared the morning of the resignation.", itm: ["IF002", "PR003", "AF014"], terms: ["rclone sync personal dropbox", "assay protocol archive", "after-hours staging", "shell history cleared"], facts: [["ACTOR", "Principal scientist · departing"], ["METHODS", "rclone sync · after-hours archive staging"], ["EXFIL", "Personal Dropbox (41 GB)"], ["DETECTED VIA", "Cloud-app audit logs · endpoint telemetry"], ["OUTCOME", "TRO granted · expedited discovery"]] },
    { id: "2026-0801-7QN", kind: "CASE", title: "United States v. Okafor", channel: "filings", sig: 88, strength: "CONFIRMED IN COURT", source: "COURTLISTENER RECAP", docket: "S.D.N.Y. 1:26-CR-00589", filed: "2026-08-01", retrieved: "2026-08-08 03:11Z", insiderType: "malicious", note: "Former infrastructure lead retained a dormant domain-admin account after termination and used it six weeks later to disable backup jobs and delete hypervisor volumes. Windows security logs on two jump hosts were cleared during the intrusion.", itm: ["ME024", "AF014"], terms: ["dormant domain admin", "post-termination auth", "backup jobs disabled", "event log 1102"], facts: [["ACTOR", "Infrastructure lead · former (6 wks)"], ["METHODS", "Retained admin account · remote access"], ["IMPACT", "Hypervisor volumes deleted · 3-day outage"], ["DETECTED VIA", "Off-host log forwarding"], ["OUTCOME", "Guilty plea · CFAA §1030(a)(5)"]] },
    { id: "2026-0804-2RD", kind: "NEWS", title: "Quant fund alleges departing engineer took pricing models to rival", channel: "news", sig: 74, strength: "ALLEGED", source: "SECURITYWEEK", docket: null, filed: "2026-08-04", retrieved: "2026-08-04 18:05Z", insiderType: "malicious", note: "Complaint reportedly describes a 2 AM download of model repositories and a zip archive named after the engineer's start date at the rival firm. Filing not yet in RECAP; watching the docket.", itm: ["IF002", "PR003"], terms: ["model repository clone", "named zip archive", "2am download window"], facts: [["ACTOR", "Quant engineer · departing"], ["METHODS", "Repo clone · local archive"], ["STATUS", "Complaint reported · docket watch active"]] },
    { id: "2026-0729-D1X", kind: "CASE", title: "Solara Energy Corp. v. Vance", channel: "filings", sig: 86, strength: "CONFIRMED IN COURT", source: "COURTLISTENER RECAP", docket: "D. ARIZ. 2:26-CV-03318", filed: "2026-07-29", retrieved: "2026-08-02 09:47Z", insiderType: "malicious", note: "Regional sales director forwarded the full customer list and pending-bid pricing to a personal Gmail address across 14 messages in her final week, then presented the same accounts at a competitor within a month.", itm: ["IF001"], terms: ["forwarded to personal gmail", "customer list attachment", "final week window"], facts: [["ACTOR", "Sales director · departing"], ["METHODS", "Self-addressed email · 14 messages"], ["EXFIL", "Personal Gmail"], ["DETECTED VIA", "Mail gateway archive"], ["OUTCOME", "Preliminary injunction granted"]] },
    { id: "2026-0807-9QZ", kind: "SOCIAL", title: "r/overemployed: “J2 laptop and J1 laptop on the same desk, one jiggler each”", channel: "social", sig: 63, strength: "REPORTED", source: "REDDIT r/overemployed", docket: null, filed: "2026-08-07", retrieved: "2026-08-07 21:14Z", insiderType: "negligent", note: "First-person account of running two concurrent remote roles with input-automation hardware to defeat idle detection, plus calendar tactics for overlapping standups. Corroborates the IF038 pattern the filings lane sees post-hoc.", itm: ["IF038"], terms: ["mouse jiggler", "overlapping meetings", "j1 and j2"], facts: [["ACTOR", "IC engineer · current, dual-employed"], ["METHODS", "Input automation · calendar management"]] },
    { id: "2026-0803-4LM", kind: "SOCIAL", title: "r/sysadmin: analyst pasted M&A deck into a personal AI chatbot", channel: "social", sig: 58, strength: "REPORTED", source: "REDDIT r/sysadmin", docket: null, filed: "2026-08-03", retrieved: "2026-08-03 16:40Z", insiderType: "unintentional", note: "Thread describes a corp-dev analyst pasting a confidential M&A deck into a consumer AI tool to “clean up the wording”; caught by proxy inspection. No malice indicated — policy gap plus deadline pressure.", itm: ["ME030"], terms: ["pasted into chatbot", "consumer ai endpoint", "proxy post body"], facts: [["ACTOR", "Corp-dev analyst · current"], ["METHODS", "Consumer AI paste"], ["DETECTED VIA", "Forward proxy inspection"]] },
    { id: "2026-0725-B8T", kind: "CASE", title: "In re Halvorsen Logistics Data Incident", channel: "filings", sig: 71, strength: "ALLEGED", source: "COURTLISTENER RECAP", docket: "N.D. ILL. 1:26-CV-08812", filed: "2026-07-25", retrieved: "2026-07-30 11:02Z", insiderType: "negligent", note: "Warehouse contractor allegedly used a supervisor's shared terminal login for months; the account later appears in an unauthorized bulk export of driver PII. Attribution contested precisely because the credential was communal.", itm: ["ME021"], terms: ["shared terminal login", "communal credential", "bulk pii export"], facts: [["ACTOR", "Contractor · current"], ["METHODS", "Shared supervisor login"], ["IMPACT", "Driver PII export · attribution contested"]] },
    { id: "2026-0731-6VW", kind: "NEWS", title: "Hospital clerk fired after browsing 900+ patient records outside caseload", channel: "news", sig: 66, strength: "REPORTED", source: "DATABREACHES.NET", docket: null, filed: "2026-07-31", retrieved: "2026-07-31 22:26Z", insiderType: "malicious", note: "Access-log review found systematic lookups of neighbors, coworkers, and a former spouse over 18 months. Classic ME027 curve: low volume per day, extreme cumulative deviation from role baseline.", itm: ["ME027"], terms: ["record snooping", "role baseline deviation", "access log review"], facts: [["ACTOR", "Records clerk · current"], ["METHODS", "Authorized credential · out-of-scope lookups"], ["DETECTED VIA", "HIPAA access-log audit"], ["OUTCOME", "Terminated · state AG referral"]] }
  ],
  trail: [["Cloud / SaaS audit logs", 62, 44], ["Endpoint forensics", 48, 39], ["Mail gateway archives", 41, 33], ["Server & application logs", 37, 26], ["Badge / physical records", 18, 12], ["Financial & public records", 16, 14]],
  actors: { fn: [["Technical / engineering", 38], ["Sales & commercial", 22], ["Executive / officer", 14], ["Operations / clerical", 13], ["Finance", 8], ["Other / unknown", 5]], state: [["Departing (notice period)", 34], ["Current", 41], ["Former (post-separation)", 25]] },
  findings: [
    { id: "F-2026-014", claim: "The notice period is the highest-risk window: a third of method-bearing cases show exfiltration between resignation and last day.", caveat: "Of litigated cases — departures are also when firms look hardest.", rec: "Stand up a departing-employee egress review as a standing control, not an investigation trigger." },
    { id: "F-2026-011", claim: "Cloud-app audit logs are the single most probative record class, appearing in the proof chain of 44% of cases confirmed in court.", caveat: "Reflects what survives to court, not what detects earliest.", rec: "Treat cloud-tenant audit retention as evidence infrastructure; 12-month minimum." }
  ]
};
